var parkOptions = [
	{value : 'all', label : 'Choose an option', icon : 'none'},
    	{value : 'Baseball_F', label : 'Baseball/Softball Fields', icon : 'baseball.png'},
    	{value : 'Basketball', label : 'Basketball Courts', icon : 'basketballfield.png'},
	{value : 'Climbing_Wall', label : 'Climbing Wall', icon : 'climbing_wall.png'},
    	{value : 'Cycling', label : 'Cycling Paths', icon : 'cycling.png'},
	{value : 'Disc_Golf', label : 'Disc Golf', icon : 'discgolf.png'},
    	{value : 'Dog_Park', label : 'Dog Parks', icon : 'dogs_leash.png'},
	{value : 'Gym', label : 'Gym Center', icon : 'basketballfield.png'},
    	{value : 'Grills', label : 'Grills', icon : 'grill.png'},
	{value : 'Field', label : 'Multi-use Sports Fields', icon : 'soccer.png'},
	{value : 'Open_Play', label : 'Open Play', icon : 'urbanpark.png'},
    	{value : 'Picnic_She', label : 'Picnic Shelters', icon : 'picnicShelter.png'},
    	{value : 'Picnic_Tab', label : 'Picnic Tables', icon : 'picnicTable.png'},
    	{value : 'Playrgound', label : 'Playgrounds', icon : 'playground.png'},
	{value : 'Pool', label : 'Pool', icon : 'pool.png'},
    	{value : 'Restrooms', label : 'Restrooms', icon : 'toilets.png'},
    	{value : 'Recreation', label : 'Recreation Center', icon : 'communitycentre.png'},
	{value : 'Splasheville', label : 'Splasheville', icon : 'splasheville.png'},
    	{value : 'Tennis_Cou', label : 'Tennis Court', icon : 'tennis.png'},
	{value : 'Velodrome', label : 'Velodrome', icon : 'velodrome.png'},
	{value : 'Volleyball', label : 'Volleyball', icon : 'volleyball.png'},
    	{value : 'Multi_Use_', label : 'Walking Paths', icon : 'walkingtour.png'},
    	{value : 'WI_FI', label : 'Wi-Fi', icon : 'wi-fi.png'}   
];
